name: CI

on:
  push:
    branches: [ main, ms1 ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps (root)
        run: npm ci

      - name: Install deps (client)
        run: npm ci --prefix client

      - name: Backend tests
        run: npm run test:backend --silent

      - name: Frontend tests
        run: npm run test:frontend --silent

      - name: Upload coverage (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            server/coverage
            client/coverage
